---
title: "day7-interactive"
output: html_document
date: "2025-08-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(lubridate)
library(datapasta)
```

```{r}


penguins_clean <- penguins %>% 
  filter(island == "Biscoe" | island == "Dream") %>% 
  select(1:6) %>% 
  mutate(body_mass_kg = body_mass_g / 1000) %>% 
  rename(location = "island")
  
  
  
```

```{r}
penguins_sum <- penguins %>% 
  filter(species == "Adelie", !is.na(flipper_length_mm)) %>% 
  group_by(sex) %>% 
  summarise(mean_flipper_length_mm = mean(flipper_length_mm),
            sd_flipper_length_mm = sd(flipper_length_mm),
            sample_size = n())
  
  
  
```

```{r}
animals <-data.frame(
  stringsAsFactors = FALSE,
          location = c("lagoon", "bluff", "creek", "oaks", "bluff"),
           species = c("bobcat", "coyote", "fox", "squirrel", "bobcat"),
          maturity = c("adult", "juvenile", "adult", "juvenile", "adult")
)

sites <- data.frame(
  stringsAsFactors = FALSE,
          location = c("beach", "lagoon", "bluff", "oaks"),
    full_site_name = c("Goleta Beach","UCSB Lagoon",
                       "Ellwood Mesa","Fremont Campground"),
      jurisdiction = c("SB City", "UCSB", "SB City", "USFS")
)


```

```{r}
#keeps all rows and adds all columns
full_join_example <- full_join(animals, sites)
```

```{r}
#keeps all left rows and adds matching columns from sites
left_join_example <- left_join(animals, sites)

#keeps all right rows and adds matching columns from animals
right_join_example <- right_join(animals, sites)

#keeps only matching rows from left and adds matching columns from sites
inner_join_example <- inner_join(animals, sites)

#keeps only matching rows from left but does not add columns from sites
semi_join_example <- semi_join(animals, sites)

#same as
animals %>% 
  filter(location %in% sites$location)

#keeps non matching rows from left and does not add columns from sites
anti_join_example <- anti_join(animals, sites)

#same as
animals %>% 
  filter(!location %in% sites$location)

```
```{r}
my_date <- "03-15-1998"

lubridate::mdy(my_date)

```
```{r}
my_date <- "4/Dec/2001"

lubridate::dmy(my_date)
```

```{r}
my_date <- "19610518"

lubridate::ymd(my_date)
```

```{r}
lubridate::dmy("09/12/84")
```
##date that doesn't make sense
```{r}
time <- "2020-08-12 11:18"

ymd_hm(time)

with_tz(time, "America/Los Angeles")
```
```{r}
week(time)

```
```{r}
start_time <- Sys.time()

end_time <- Sys.time()

end_time - start_time
```

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_counts_ymd <- urchin_counts %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(year = year(date),
         month = month(date),
         day = day(date))

urchin_counts_ymd
```
```{r}
day_1 <- lubridate::ymd("2020-01-06")

day_2 <- ymd("2020-05-18")

day_3 <- ymd("2020-05-19")

time_interval <- interval(day_1, day_2)
time_length(time_interval, "week")
```

```{r}
#str_detect returns T/F based on if the string is present or not
my_string <- "Teddy loves eating salmon and socks"


my_string %>% 
  str_detect("love")
```

```{r}
my_food <- c("burrito", "fish taco", "taco salad")

my_food %>% 
  str_detect("fish")
```

```{r}
starwars %>% 
  filter(str_detect(name, "Skywalker"))
```

```{r}
firewalker <-  starwars %>% 
  mutate(name = str_replace(name, pattern = "Sky", replacement = "Fire"))
```

